### ISSUE TITLE
Question: Magic configure method

### ISSUE THREAD

**Issue by dsvoronin** [foo4u/gradle-semver-plugin#4]
@foo4u I'm totally confused. You have method
[`void configure(Map<String,?> map)`](https://github.com/foo4u/gradle-semver-plugin/blob/master/src/main/groovy/io/fugu/gradle/plugns/version/SemanticVersion.groovy#L15) that appears to be never called.
I'm developing same plugin for android right now, and need sort of callback for version set.
So i wonder how this magic works in your code?

**Comment by foo4u** [comment]
``` groovy
project.version.with { major = 1; minor = 2; revision = 15  }
```

When this closure is invoked, Gradle calls the configure method you mentioned. This may not be ideal but it works.
